services:
  miniflux:
    image: miniflux/miniflux:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    ports:
      - "8082:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RUN_MIGRATIONS=1
