services:
  server:
    image: docker.gitea.com/gitea:1.25.3
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${DATABASE_HOST}
      - GITEA__database__NAME=${DATABASE_NAME}
      - GITEA__database__USER=${DATABASE_USER}
      - GITEA__database__PASSWD=${DATABASE_PASS}
      - GITEA__database__SSL=on
    restart: unless-stopped
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
