services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - 3005:3000
    volumes:
      - ./data:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: terra:3005,home.taiidani.com,taiidani.com # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
