services:
  radarr:
    image: ghcr.io/hotio/radarr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=7878/tcp
    volumes:
      - ./data/radarr:/config
      - /mnt/storage/content:/data
      - /mnt/storage/downloads:/downloads

  sonarr:
    image: ghcr.io/hotio/sonarr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8989/tcp
    volumes:
      - ./data/sonarr:/config
      - /mnt/storage/content:/data
      - /mnt/storage/downloads:/downloads
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - ./data/qbittorrent:/config
      - /mnt/storage/downloads:/downloads #optional

  gluetun:
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
    ports:
      # All qBittorrent ports
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      # Radarr
      - "7878:7878"
      # Sonarr
      - "8989:8989"
      # Prowlarr
      - "9696:9696"

  prowlarr:
    image: ghcr.io/hotio/prowlarr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=9696/tcp
    volumes:
      - ./data/prowlarr:/config
