name: lil-dumpster

services:
  lil-dumpster:
    image: ghcr.io/team-dumpster-fire/lil-dumpster:latest
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis.lil-dumpster_default
      REDIS_PORT: 6379
      DISCORD_TOKEN: "${DISCORD_TOKEN}"

  redis:
    image: redis:6
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
